# Generated by Django 5.2.7 on 2025-10-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the row was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField(help_text='The prompt question or statement for users', verbose_name='prompt text')),
                ('scheduled_date', models.DateField(blank=True, help_text='Date when this prompt should be displayed', null=True, verbose_name='scheduled date')),
            ],
            options={
                'verbose_name': 'daily prompt',
                'verbose_name_plural': 'daily prompts',
                'db_table': 'daily_prompts',
                'ordering': ['-created_at'],
            },
        ),
    ]
