# Generated by Django 5.2.7 on 2025-10-08 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'prompt categories',
                'db_table': 'prompt_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailyprompt',
            options={'ordering': ['category', 'difficulty']},
        ),
        migrations.RemoveField(
            model_name='dailyprompt',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='dailyprompt',
            name='text',
        ),
        migrations.AddField(
            model_name='dailyprompt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyprompt',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('deep', 'Deep')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyprompt',
            name='question',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dailyprompt',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dailyprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailyprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CustomPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyprompt',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.promptcategory'),
        ),
        migrations.AddIndex(
            model_name='dailyprompt',
            index=models.Index(fields=['category', 'is_active'], name='daily_promp_categor_b74db5_idx'),
        ),
    ]
