# Generated by Django 5.2.7 on 2025-11-11 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_promptcategory_alter_dailyprompt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customprompt',
            index=models.Index(fields=['user', 'is_active'], name='custom_prom_user_id_802c55_idx'),
        ),
        migrations.AddIndex(
            model_name='customprompt',
            index=models.Index(fields=['is_recurring', 'is_active'], name='custom_prom_is_recu_c6ed73_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprompt',
            index=models.Index(fields=['is_active', 'difficulty'], name='daily_promp_is_acti_e1973d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprompt',
            index=models.Index(fields=['created_at'], name='daily_promp_created_a38fda_idx'),
        ),
    ]
