# Generated by Django 5.2.7 on 2025-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20251009_1259'),
        ('prompts', '0003_customprompt_custom_prom_user_id_802c55_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprompt',
            name='tags',
        ),
        migrations.AddField(
            model_name='dailyprompt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='daily_prompts', to='journals.tag'),
        ),
    ]
