# Generated by Django 5.2.7 on 2025-10-08 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('factor_type', models.CharField(choices=[('sleep', 'Sleep'), ('exercise', 'Exercise'), ('social', 'Social Interaction'), ('work', 'Work/Productivity'), ('weather', 'Weather'), ('health', 'Physical Health'), ('stress', 'Stress Level'), ('diet', 'Diet/Nutrition'), ('medication', 'Medication'), ('other', 'Other')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_system', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mood_factors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'mood categories',
                'db_table': 'mood_categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='mood_catego_is_acti_bb3528_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomMoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_mood_categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='custom_mood_user_id_0844e5_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
