# Generated by Django 5.2.7 on 2025-10-08 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('csv', 'CSV'), ('markdown', 'Markdown')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('include_photos', models.BooleanField(default=True)),
                ('include_voice_notes', models.BooleanField(default=False)),
                ('include_mood_data', models.BooleanField(default=True)),
                ('include_focus_data', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('processing_time_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='export_requ_user_id_79d84b_idx'), models.Index(fields=['status', 'created_at'], name='export_requ_status_1674df_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('export_type', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('csv', 'CSV'), ('markdown', 'Markdown')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('include_photos', models.BooleanField(default=True)),
                ('include_voice_notes', models.BooleanField(default=False)),
                ('include_mood_data', models.BooleanField(default=True)),
                ('include_focus_data', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_exports',
                'ordering': ['next_run_at'],
                'indexes': [models.Index(fields=['next_run_at', 'is_active'], name='scheduled_e_next_ru_2dee2b_idx')],
            },
        ),
    ]
