# Generated by Django 5.2.7 on 2025-10-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='journalpromptresponse',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='journalvoicenote',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='journalpromptresponse',
            name='prompt',
        ),
        migrations.DeleteModel(
            name='JournalPhoto',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalVoiceNote',
        ),
        migrations.DeleteModel(
            name='JournalPromptResponse',
        ),
    ]
