# Generated by Django 3.2.25 on 2025-10-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_remove_journalentry_tags_remove_journalentry_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytemplate',
            name='usage_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='entrytemplate',
            index=models.Index(fields=['user', '-usage_count'], name='entry_templ_user_id_d24e79_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tags_user_id_eb4e0f_idx'),
        ),
    ]
