# Generated by Django 5.2.7 on 2025-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focuspause',
            name='session',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='program_day',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='user_program',
        ),
        migrations.AlterUniqueTogether(
            name='userprogramday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogramday',
            name='program_day',
        ),
        migrations.RemoveField(
            model_name='userprogramday',
            name='user_program',
        ),
        migrations.RemoveField(
            model_name='userfocusprogram',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='userfocusprogram',
            name='days_completed',
        ),
        migrations.RemoveField(
            model_name='userfocusprogram',
            name='total_focus_minutes',
        ),
        migrations.AlterField(
            model_name='userfocusprogram',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20),
        ),
        migrations.DeleteModel(
            name='FocusGoal',
        ),
        migrations.DeleteModel(
            name='FocusPause',
        ),
        migrations.DeleteModel(
            name='FocusSession',
        ),
        migrations.DeleteModel(
            name='UserProgramDay',
        ),
    ]
