# Generated by Django 5.2.7 on 2025-12-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_remove_focuspause_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programday',
            name='is_ritual',
            field=models.BooleanField(default=False, help_text='If True, uses step-based flow instead of tasks'),
        ),
        migrations.CreateModel(
            name='ProgramStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the row was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('step_type', models.CharField(choices=[('breathing', 'Breathing Exercise'), ('gratitude', 'Gratitude Entry'), ('affirmation', 'Affirmation Selection'), ('prompt', 'Reflection Prompt'), ('task', 'Simple Task'), ('meditation', 'Meditation'), ('journaling', 'Journaling'), ('checkin', 'Mood Check-in')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('duration_seconds', models.IntegerField(default=60, help_text='Duration in seconds')),
                ('input_type', models.CharField(choices=[('none', 'No Input'), ('text', 'Text Input'), ('voice', 'Voice Note'), ('text_voice', 'Text or Voice'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('rating', 'Rating Scale'), ('slider', 'Slider')], default='none', max_length=20)),
                ('placeholder_text', models.CharField(blank=True, max_length=300)),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of choice options')),
                ('prompts', models.JSONField(blank=True, default=list, help_text='Rotating prompts')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Step-specific config like animation type, icon, color')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('background_color', models.CharField(blank=True, max_length=7)),
                ('is_required', models.BooleanField(default=True)),
                ('is_skippable', models.BooleanField(default=False)),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='focus.programday')),
            ],
            options={
                'db_table': 'program_steps',
                'ordering': ['program_day', 'order'],
                'unique_together': {('program_day', 'order')},
            },
        ),
    ]
