# Generated by Django 5.2.7 on 2025-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_add_program_step_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusprogram',
            name='program_type',
            field=models.CharField(choices=[('14_day', '14-Day Program'), ('30_day', '30-Day Program'), ('custom', 'Custom Program'), ('morning_ritual', 'Morning Ritual'), ('brain_dump', 'Brain Dump'), ('gratitude', 'Gratitude Pause'), ('evening_ritual', 'Evening Ritual')], max_length=20),
        ),
    ]
