# Generated by Django 3.2.25 on 2025-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_premium_programs'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='premiumprogramtrial',
            name='premium_pr_user_id_trial_e_idx',
        ),
        migrations.RemoveIndex(
            model_name='premiumprogramtrial',
            name='premium_pr_trial_e_idx',
        ),
        migrations.AlterField(
            model_name='braindumpcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the row was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='braindumpcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='premiumprogramtrial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time at which the row was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='premiumprogramtrial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time at which the row was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='premiumprogramtrial',
            index=models.Index(fields=['user', 'trial_ends_at'], name='premium_pro_user_id_94a69e_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumprogramtrial',
            index=models.Index(fields=['trial_expired'], name='premium_pro_trial_e_3dde7f_idx'),
        ),
    ]
