# Generated by Django 3.2.25 on 2025-12-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_auto_20251202_0057'),
        ('focus', '0004_update_program_types'),
    ]

    operations = [
    ]
